spring:
  application:
    name: hello-sprint-boot

server:
  port: 8081


DB_URL: jdbc:postgresql://localhost:5434/
DB_NAME: postgres
DB_USERNAME: postgres
DB_PASSWORD: a
DB_DRIVER_CLASSNAME: org.postgresql.Driver
